### PR TITLE
Added parameterized SHA modules

### PR DESCRIPTION
**Pull request by weaversa**

### CODE REVIEW

**Comment by brianhuffman** [comment]
@atomb We should not have merged this pull request without testing it first. We really need some regression tests to avoid mistakes like this. (GaloisInc/cryptol#571)

**Comment by brianhuffman** [comment]
Several of the new files contain apparently-identical copies of a large constant table `K`. This level of duplication is an unpleasant code smell.

**Comment by weaversa** [comment]
> Several of the new files contain apparently-identical copies of a large constant table `K`. This level of duplication is an unpleasant code smell.

The K constants come from page 11 and 12 from here: https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.180-4.pdf

**Comment by brianhuffman** [comment]
My point is that the cryptol-specs repo should only need to have one copy of each constant table. If it's not easy to accomplish that with the current design for parameterized modules, then we need to rethink the design of that feature.

The docstring for the table should also have a link to the authoritative reference document name and section number (e.g. FIPS 180-4, section 4.2). (And we ought to document this practice in the repository's style guide, see #5.)

**Comment by weaversa** [comment]
Is it possible to partially instantiate a parameterized module? If so, We could first create two partial instantiations of sha, one for each constant `k`, and then create the top 6 modules from those 2.

**Comment by weaversa** [comment]
Also, in this particular instance, the smaller table is just a abbreviation of the larger table. So, SHA.cry could have the larger table hardcoded, and then reshape it as needed according to it's `j` and `w` parameters.

**Pull request merged**
